=== thegoose20/neh/neh-data/NEH_GrantProducts/NEH_Equipment.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Equipment">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ApplicationNumber" type="xs:string"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="Location" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Year" type="xs:unsignedInt"/>
						</xs:sequence>
						<xs:attribute name="ID" type="xs:unsignedInt" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thegoose20/neh/neh-data/NEH_GrantProducts/NEH_Equipment.xml
<Equipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NEH_Equipment.xsd">
	<Item ID="1292">
		<ApplicationNumber>PA-51137-05</ApplicationNumber>
		<Description>Purchase of UV roller shades and 90% UV protection broze mylar shades</Description>
		<Location>Wentworth Coolidge Mansion State Historic Site, Portsmouth NH</Location>
		<Name>Light Protection</Name>
		<Year>2006</Year>
	</Item>
	<Item ID="14036">
		<ApplicationNumber>PG-252807-17</ApplicationNumber>
		<Description>Dahle Premium 43" Large Format Guillotine Paper Trimmer</Description>
		<Location>Edmond, OK</Location>
		<Name>Dahle Large Format paper trimmer</Name>
		<Year>2017</Year>
	</Item>
	<Item ID="15594">
		<ApplicationNumber>PG-258259-18</ApplicationNumber>
		<Description>Two five-drawer flat file cabinets used for storage of oversize collection materials, such as maps, posters, certificates and photographs, and a library ladder.</Description>
		<Location>Basque Museum &amp;amp; Cultural Center, Boise, Idaho</Location>
		<Name>Flat file cabinets and library ladder</Name>
		<Year>2018</Year>
	</Item>
	<Item ID="16674">
		<ApplicationNumber>PG-263474-19</ApplicationNumber>
		<Description>100 count unbuffered 10 pt. folder stock, used to create enclosures for oversized building plans and landscape drawings</Description>
		<Location>Rod Library, University of Northern Iowa (Cedar Falls, IA)</Location>
		<Name>folder stock</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="16685">
		<ApplicationNumber>PG-263605-19</ApplicationNumber>
		<Description>Wall hanging system for rolled textile collections abd a PEM2 datalogger for environmental monitoring of the new storage area</Description>
		<Location>Archives, University Library, Colorado State University-Pueblo</Location>
		<Name>Shelving and Environmental Monitor</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="16699">
		<ApplicationNumber>PG-266577-19</ApplicationNumber>
		<Description>Mega Safe Burglary &amp;amp; Fire Safe Cabinet MBF2020E 2 Hr Fire Rating, Digital Lock, 22"W x 22"D x 22-1/2" H</Description>
		<Location>John Hair Cultural Center &amp;amp; Museum, Tahlequah, OK</Location>
		<Name>Mega Safe</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="16962">
		<ApplicationNumber>PG-266753-19</ApplicationNumber>
		<Description>Archival quality, powder coated, lockable, storage cabinet for three-dimensional artwork</Description>
		<Location>Utah</Location>
		<Name>Archival Storage Cabinet</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="17043">
		<ApplicationNumber>PG-266736-19</ApplicationNumber>
		<Description>Light meters and data loggers to monitor the environment in the library, museum and 2 historic houses</Description>
		<Location>Luzerne County Historical Society Library, Museum, Nathan Denison House, Swetland Homestead</Location>
		<Name>Lux Light Meter and MX1101 data logger</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="17089">
		<ApplicationNumber>PG-266620-19</ApplicationNumber>
		<Description>Two (2) units of Montel High Density Mobile Shelving installed on an existing track system in the AMC Library &amp;amp; Archives to accomodate 224 cubic feet of archives collections materials.</Description>
		<Location>Appalachian Mountain Club Library &amp;amp; Archives, AMC Highland Center at Crawford Notch, Bretton Woods, New Hampshire</Location>
		<Name>Two (2) units of Montel High Density Mobile Shelving</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="17141">
		<ApplicationNumber>PG-266611-19</ApplicationNumber>
		<Description>Specialty shelving for fine-arts storage</Description>
		<Location>Boston, MA</Location>
		<Name>Shelving for large framed prints/paintings</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="17186">
		<ApplicationNumber>PG-266735-19</ApplicationNumber>
		<Description>Archival steel mobile compact shelving that moves on rails.</Description>
		<Location>329 W. 18th Street  Suite 302 Chicago, IL  60616</Location>
		<Name>Archival shelving</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="17232">
		<ApplicationNumber>PG-266715-19</ApplicationNumber>
		<Description>The equipment comprised five Disaster Response Supply Cans containing the following emergency supplies (see photos in Article):  CONTAINERS 15-gallon bucket 133-gallon trash can 10Large plastic trash bags and 14" zip ties GENERAL SUPPLIES  1notepad 2 markers 1 boxSharpened pencils 2scissors 1Packing tape dispenser and 2 rolls of tape 1Box cutter with 2 replacement blades inside 1 rollDuct tape 1Self-standing Atomic Beam lantern w/batteries 3AAA backup batteries (attached to inside of trash can lid)  150-ft extension cord FOR LEAKS OR PROTECTION FROM SPRINKLERS 1 roll10' x 100' 4mil plastic sheeting 1 spoolNylon string (to hang sheeting) 2Large sponges 2 rollsPaper towels 5New Pig re-usable absorbent socks (blue) 20New Pig disposable absorbent mats (black) FOR PERSONAL PROTECTION 2 pairsLeather gloves 1 boxNitrile gloves 10 Plastic smocks 1 boxN95 masks 2Plastic goggles</Description>
		<Location>Santa Rosa, Petaluma, Healdsburg, and Rohnert Park of California</Location>
		<Name>Disaster Response Supply Cans</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="17277">
		<ApplicationNumber>PG-262249-19</ApplicationNumber>
		<Description>1 (one) Montel High Density Mechanical Assist Mobile Shelving Carriage added to existing floor rail and shelving system.</Description>
		<Location>Appalachian Mountain Club Library &amp;amp; Archives, AMC Highland Center at Crawford Notch, Bretton Woods, New Hampshire</Location>
		<Name>Montel High Density Mobile Shelving</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="18075">
		<ApplicationNumber>PF-266604-19</ApplicationNumber>
		<Description>Upon receipt of the grant in late 2019, the Poetry Center worked with Phoenix-based firm Interior Solutions to design a Spacesaver mechanical-assist high-density mobile storage system for the Poetry Center's Archives Room. Funding from the NEH was used to purchase this system, which added 1200 linear feet of shelving space to our Archives storage capacity.</Description>
		<Location>The University of Arizona Poetry Center, Tucson, Arizona</Location>
		<Name>Spacesaver Mechanical-Assist High-Density Storage</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="18137">
		<ApplicationNumber>PF-266683-19</ApplicationNumber>
		<Description>Two Daikin chillers were purchased, installed, and connected to system controls to improve temperature and relative humidity controls at the Chicago History Museum's main facility.</Description>
		<Location>Chicago History Museum, 1601 N. Clark St., Chicago IL</Location>
		<Name>Daikin chillers</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="18229">
		<ApplicationNumber>PG-271695-20</ApplicationNumber>
		<Description>REACH-IN FREEZER  True Manufacturing Co., Inc. Model No. 4024928 Freezer, reach-in, two-section, -10°F, (2) stainless steel doors, (6) PVC coated adjustable wire shelves, interior lighting, stainless steel front, aluminum sides, aluminum interior with stainless steel floor, 4" castors, R290 Hydrocarbon refrigerant, 1 HP, 115v/60/1-ph, 9.6 amps, NEMA 5-15P, Made in USA, cULus, UL EPH Classified, ENERGY STAR® Dimensions 78.38(h) x 54.13(w) x 29.5(d)  REACH-IN REFRIGERATOR  True Manufacturing Co., Inc. Model No. 3547083 Refrigerator, reach-in, three-section, (3) stainless steel doors, (9) PVC coated adjustable wire shelves, interior lighting, stainless steel front, aluminum sides, aluminum interior with stainless steel floor, 4" castors, R290 Hydrocarbon refrigerant, 3/4 HP, 115v/60/1-ph, 6.9 amps, NEMA 5-15P, cULus, UL EPH Classified, Made in USA Dimensions 78.38(h) x 78.13(w) x 29.5(d) Weight: 575 lbs total</Description>
		<Location>CFA  329 W. 18th Street  #317, Chicago, IL  60616</Location>
		<Name>Refrigerator and Freezer</Name>
		<Year>2020</Year>
	</Item>
	<Item ID="18382">
		<ApplicationNumber>AV-265985-19</ApplicationNumber>
		<Description>Purchased 3 desktop computers</Description>
		<Location>Veterans Resource Center</Location>
		<Name>Desktop Computers</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="18728">
		<ApplicationNumber>PG-263619-19</ApplicationNumber>
		<Description>Acquisition of two 'Just-in-case Case Disaster Kit' which is a complete disaster preparedness kit with a in a medium size. Supplied as two boxes, no transit trolley. A vas variety of supplies need in one place, sealed to ensure items are not removed until required. The 34 piece kit comprised of 273 individual items, covering Personal Protective Equipment, Clean-up, Survey and Damage Recording, Illumination, Water Barriers and absorbent materials, and emergency tools. The kit has been created with the experience and support of conservators, curators, archivists, librarians and collection managers. The kit is designed to be used primarily by a 2 person team and provides a range of items to prevent further damage, document damage and then clean-up. The just-in-case disaster supplies kit is intended for use in small scale disasters such as flooding, exposure to elements or dust ingress. Each kit is sealed to prevent misuse of contents.</Description>
		<Location>In the Museo de Arte de Puerto Rico "Sala de estudio e investigación" library and the "Centro de docuentación y estudios curatoriales" archive.</Location>
		<Name>Disaster preparedness kit</Name>
		<Year>2021</Year>
	</Item>
	<Item ID="18881">
		<ApplicationNumber>PG-266728-19</ApplicationNumber>
		<Description>Onset Environmental Data Loggers used to track the temperature/humidity levels every 15 minutes.</Description>
		<Location>Travellers Rest Historic House Museum, Nashville, TN</Location>
		<Name>Onset Data Loggers</Name>
		<Year>2019</Year>
	</Item>
	<Item ID="18940">
		<ApplicationNumber>PG-271818-20</ApplicationNumber>
