=== thegoose20/neh/neh-data/NEH_GrantProducts/NEH_Positions.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Positions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Position" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ApplicationNumber" type="xs:string"/>
							<xs:element name="Abstract" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="PrimaryURL" type="xs:string"/>
							<xs:element name="PrimaryURLDescription" type="xs:string"/>
							<xs:element name="SecondaryURL" type="xs:string"/>
							<xs:element name="SecondaryURLDescription" type="xs:string"/>
							<xs:element name="Year" type="xs:unsignedInt"/>
						</xs:sequence>
						<xs:attribute name="ID" type="xs:unsignedInt" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thegoose20/neh/neh-data/NEH_GrantProducts/NEH_Positions.xml
<Positions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NEH_Positions.xsd">
	<Position ID="116">
		<ApplicationNumber>CH-50424-07</ApplicationNumber>
		<Abstract>Mars Hill College hired Dr. Karen Paar as Director of the Liston B. Ramsey Center for Regional Studies and Archivist for the Southern Appalachian Archives.  Dr. Paar has done an outstanding job in the position and has led the Ramsey Center and the Southern Appalachian Archives into a new era of professionalism and increased visibility.</Abstract>
		<Name>Ramsey Center for Regional Studies Director and Archivist for the Southern Appalachian Archives</Name>
		<PrimaryURL>http://www.mhc.edu/ramsey-center</PrimaryURL>
		<PrimaryURLDescription>This is the website for the Ramsey Center.  It offers a brief introduction to the Center's work, all of which Dr. Paar has spearheaded.  </PrimaryURLDescription>
		<SecondaryURL>http://www.mhc.edu/ramsey-center/southern-appalachian-archives</SecondaryURL>
		<SecondaryURLDescription>This is the website for the Southern Appalachian Archives, which houses archival treasures of national importance, and which Dr. Paar stewards.  </SecondaryURLDescription>
		<Year>2007</Year>
	</Position>
	<Position ID="180">
		<ApplicationNumber>RA-50033-05</ApplicationNumber>
		<Abstract>John &amp;amp; Anne Fischer Professorship in Fine Arts, Hamilton College</Abstract>
		<Name>John C. McEnroe</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2005</Year>
	</Position>
	<Position ID="181">
		<ApplicationNumber>RA-50033-05</ApplicationNumber>
		<Abstract>Stipendiary Faculty Fellow, The Melbern G. Glasscock Center for Humanities Research, Texas A&amp;amp;M University. Awarded in Architecture for "Architectural Development of the Athenian Acropolis in the Archaic and Early Classical Period."</Abstract>
		<Name>Nancy Klein</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2006</Year>
	</Position>
	<Position ID="207">
		<ApplicationNumber>GE-50227-10</ApplicationNumber>
		<Abstract>Ms. Arrowood served as a research assistant during the planning grant and helped to write draft narrative scripts that we serve as a starting point for developing final audio scripts during the implementation grant period.</Abstract>
		<Name>Chelsie Arrowood</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2011</Year>
	</Position>
	<Position ID="212">
		<ApplicationNumber>RA-50033-05</ApplicationNumber>
		<Abstract>Associate Professor, Harvard University, Spring 2008</Abstract>
		<Name>Betsey A. Robinson</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2008</Year>
	</Position>
	<Position ID="213">
		<ApplicationNumber>RA-50033-05</ApplicationNumber>
		<Abstract>Associate Professor, Department of History of Art, Vanderbilt University, August 2008</Abstract>
		<Name>Betsey A. Robinson</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2008</Year>
	</Position>
	<Position ID="544">
		<ApplicationNumber>CZ-50173-08</ApplicationNumber>
		<Abstract>Kathleen Tipler was appointed as the Postdoctoral Fellow for the Center for the Study of American Democracy at Kenyon College, beginning Fall 2011.  She is interested in contemporary and canonical political theory particularly democratic theory, judgment, and political agency as well as American politics and public law. In her dissertation, she considers how democracies might foster citizen judgment, examining the U.S. institutions of direct legislation and the judiciary, and interbranch relations.</Abstract>
		<Name>Postdoctoral Fellow in the Center for the Study of American Democracy </Name>
		<PrimaryURL>http://www.kenyon.edu/x58384.xml</PrimaryURL>
		<PrimaryURLDescription>Ms. Tipler's bio and link page on the Kenyon College site.</PrimaryURLDescription>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2011</Year>
	</Position>
	<Position ID="565">
		<ApplicationNumber>CH-50528-08</ApplicationNumber>
		<Abstract>ARIT Ankara hired a full-time librarian responsible for maintaining the collection and accessioning the new Mellink donation.  In addition library staffing has enabled participation in projects in collaboration with the Digital Library for International Research (DLIR).</Abstract>
		<Name>ARIT Ankara Librarian</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2007</Year>
	</Position>
	<Position ID="567">
		<ApplicationNumber>CH-50528-08</ApplicationNumber>
		<Abstract>ARIT Istanbul library has hired a professional level librarian to manage the collections in Ottoman and Byzantine studies.  The librarian also coordinates the scanning projects related to the collection of the American Board of Missions library.</Abstract>
		<Name>ARIT Istanbul librarian</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2010</Year>
	</Position>
	<Position ID="928">
		<ApplicationNumber>HD-50776-09</ApplicationNumber>
		<Abstract>Gave a presentation to the Scholar's lab and met with UVA faculty in digital humanities to discuss the development of Gibagadinamaagoom: An Ojibwe Digital Archive.  Was in residence for four days.</Abstract>
		<Name>Visiting Fellowship to UVA Scholar's Lab</Name>
		<PrimaryURL>http://www.gibagadinamaagoom.info</PrimaryURL>
		<PrimaryURLDescription>Gibagadinamaagoom: An Ojibwe Digital Archive is a website edited by Timothy B. Powell that contains materials related to Ojibwe culture from Penn Museum, Minnesota Historical Society, American Philosophical Society, National Archives, videos of Ojibwe wisdom keepers, etc.  The site has been developed with the assistance of 2 NEH HITCU grants awarded to White Earth Tribal and Community College and Leech Lake Tribal College.</PrimaryURLDescription>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2011</Year>
	</Position>
	<Position ID="1372">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>Rare book librarian, University of Michigan, Ann Arbor, MI</Abstract>
		<Name>Alvarez, Pablo</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2009</Year>
	</Position>
	<Position ID="1373">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>Alvarez, Pablo. NINES (Network Interface for Nineteenth-Century Electronic Scholarship) Miami University of Ohio, Oxford, OH</Abstract>
		<Name>Alvarez, Pablo.</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2008</Year>
	</Position>
	<Position ID="1374">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>The Humanities Project, University of Rochester: $10,000 grant for the funding of conference and exhibit, "Restoring Dryden: Music, Translation, Print."</Abstract>
		<Name>Alvarez, Pablo. </Name>
		<PrimaryURL>http://www.rochester.edu/College/humanities/projects/archive08-09.php</PrimaryURL>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2008</Year>
	</Position>
	<Position ID="1375">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>Eleanor M. Garvey Fellowship in Printing and Graphic Arts, Houghton Library, Harvard University. Research Topic: The Teaching of Hell in Sixteenth-Century Venice: The Evidence from Book Illustration and Mnemonic Treatises.</Abstract>
		<Name>Alvarez, Pablo.</Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2009</Year>
	</Position>
	<Position ID="1376">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>American Printing History Association Fellowship in Printing History (along with Keli E. Rylance, Head of the Southeastern Architectural Archives and the School of Architecture Library, Tulane University). Project: Translation and Critical Edition of Alonso Víctor de Paredes' Institución y origen del arte de la imprenta, y reglas generales para los componedores [Madrid: Alonso Víctor de Paredes, 1680].</Abstract>
		<Name>Alvarez, Pablo. </Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2010</Year>
	</Position>
	<Position ID="1385">
		<ApplicationNumber>FS-50092-06</ApplicationNumber>
		<Abstract>The Mark Samuels Lasner Fellowship in Printing History,  The American Printing History Association</Abstract>
		<Name>Rylance, Keli. (with Pablo Alvarez), </Name>
		<PrimaryURL/>
		<PrimaryURLDescription/>
		<SecondaryURL/>
		<SecondaryURLDescription/>
		<Year>2008</Year>
	</Position>
	<Position ID="1826">
		<ApplicationNumber>HB-50006-11</ApplicationNumber>
		<Abstract>This position at the Plains Indian Ledger Art website, sponsored by U of Cal-San Diego, allows me to comment upon each image of the posted ledger and also to facilitate discussion. The site also has a virtual "research station" for ongoing research with their 20 posted ledgers., Duties include commenting on the images in the ledgers and facilitating online discussion of them.</Abstract>
		<Name>Online Director for two ledgers ("Hagetta" and "Northern Cheyenne Indian") hosted by the Plains Indian Ledger Art Project (https://plainsledgerart.org/) at the University of California, San Diego. , Directorship of Plains Indian Ledger Art ledgers "Hagetta" and "Northern Cheyenne Indian"</Name>
		<PrimaryURL>https://plainsledgerart.org/ledgers/index/1/0/466  </PrimaryURL>
		<PrimaryURLDescription>PILA website -- sample page of Hagetta ledger with my name as director</PrimaryURLDescription>
		<SecondaryURL/>
		<SecondaryURLDescription/>
